---
title: "p8130 final project"
author: "chianti shi"
date: "12/8/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(haven)
library(rvest)
library(stringr)
library(forcats)
library(knitr)
library(ggplot2)
library(ggpubr)

```


Loading and cleaning the dataset
```{r, include=FALSE}
hospital_data = readxl::read_excel("./data/GHProject_Dataset.xlsx") %>%
  clean_names() %>% 
  mutate(patientid = as.character(patientid)) 

hospital_visit = hospital_data %>% 
  group_by(patientid) %>% 
  summarize(visit_num = n()) %>% 
  inner_join(hospital_data, hospital_visit, by = "patientid") %>% 
  separate(., admitdtm, into = c("dayofweek","date","year"), sep = ",") %>% 
  mutate(visit_num = as.numeric(visit_num)) 

remove_id = hospital_visit %>% 
 mutate(date = str_replace(date, "January ", "01"),
        date = str_replace(date, "February ", "02"),
        date = str_replace(date, "March ", "03"),
        date = str_replace(date, "April ", "04"),
        date = str_replace(date, "May ", "05"),
        date = str_replace(date, "June ", "06"),
        date = str_replace(date, "July ", "07"),
        date = str_replace(date, "August ", "08"),
        date = str_replace(date, "September ", "09"),
        date = str_replace(date, "October ", "10"),
        date = str_replace(date, "November ", "11"),
        date = str_replace(date, "December ", "12")) %>% 
  mutate(date = as.numeric(date)) %>% 
  arrange(date) %>% 
  group_by(patientid) %>% 
  filter(date == min(date))  
```


Select variables of interest
```{r}
#mutate mews column:   0, 1 to "1", 2,3,to "2", 4,5 to "3", 6 to "4"
# note: there are NAs in variable mews.
visit_data = remove_id %>% 
  dplyr::select(-visit_num, -dayofweek, -facilityname, -postalcode, -facilityzip) %>%
  mutate(mews, mews = ifelse( mews>5, 6, mews)) %>% 
  mutate(mews = as.character(mews)) %>% 
  mutate(mews = recode(mews, `0` = "normal", `1` = "normal", `2` = "increase_caution", `3` = "increase_caution", `4` = "further_deterioration", `5` = "further_deterioration", `6` = "immediate_action_required")) %>% 
  mutate(mews = recode(mews, `normal` = "1", `increase_caution` = "2", `further_deterioration` = "3", `immediate_action_required` = "4" ))

#mutate gender column: female:0, male:1
#note : there is no "NA" in gender variable
visit_data  = visit_data %>% 
  mutate(gender = recode(gender, `Female` = "0", `Male` = "1"))
         
#mutate race column: "White":1 "Other/Multiracial":2    "African Amer/Black":3   "Asian":4  "Native Amer/Alaskan":5  "Natv Hawaii/Pacf Isl":6
#Note: There is no NA in race variable
visit_data = visit_data %>% 
 mutate(race = recode(race, `White` = "1", `Other/Multiracial` = "2", `African Amer/Black` = "3", `Native Amer/Alaskan` = "4", `Asian` = "5", `Natv Hawaii/Pacf Isl` = "6")) 

#mutate religion: "Jewish"--1 "Catholic"--2 "Christian" ---3  "No Affiliation"---4 "Other"---5  "Islam"----6    "Hindu"----7  "Mormon"----8 "Angelican"---9  "Hebrew" ----10  "Non Denominational"----11
#Note: There is no NA in race variable
visit_data = visit_data %>% 
 mutate(religion = recode(religion, `Jewish` = "1", `Catholic` = "2", `Christian` = "3", `No Affiliation` = "4", `Other` = "5", `Islam` = "6", `Hindu` = "7", `Mormon` = "8", `Angelican` = "9", `Hebrew` = "10" , `Non Denominational` = "11")) 


#mutate maritalstatus:"Single"---1 "Married"---2 "Widowed"---3 "Divorced"---4 "Separated"---5   NA            "Civil Union"---6
#Note, there is NA in the variable
visit_data = visit_data %>%
  mutate(maritalstatus = recode(maritalstatus, `Single` = "1", `Married` = "2", `Widowed` = "3", `Divorced` = "4", `Separated` = "5", `Civil Union` = "6")) 


         

unique(visit_data$maritalstatus)

```



```{r}
summary(visit_data)
```

```{r}
par(mfrow=c(2,3))
hist(visit_data$loshours)
hist(visit_data$losdays2)
hist(visit_data$cindex)
hist(visit_data$evisit)
hist(visit_data$ageyear)
hist(visit_data$bmi)
hist(visit_data$bpsystolic)
hist(visit_data$o2sat)
hist(visit_data$temperature)
hist(visit_data$heartrate)
hist(visit_data$respirationrate)
hist(visit_data$bpdiastolic)
```

```{r warning = FALSE}
log_loshours = ggplot(data = visit_data, aes(x = log(loshours))) +
  geom_histogram() 

log_losdays2 = ggplot(data = visit_data, aes(x = log(losdays2))) +
  geom_histogram()



```


